<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ahmed Albarqi">
<meta name="dcterms.date" content="2026-01-11">

<title>Report “Fertility Rate Forecasting for Saudi Arabia”</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-99258d85ffddbd9841977770f8edb96b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../assets/css/styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Research &amp; Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../visualizations.html"> 
<span class="menu-text">Visualizations</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/asbarqi" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://substack.com/@ahmedincontext" target="_blank"> <i class="bi bi-assets/icons/substack.svg" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/asbarqi/" target="_blank"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../assets/files/Ahmed_Albarqi_CV.pdf" target="_blank"> <i class="bi bi-file-person" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Report “Fertility Rate Forecasting for Saudi Arabia”</h1>
</div>



<div class="quarto-title-meta column-page">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ahmed Albarqi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 11, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Over the past six decades, Saudi Arabia has undergone one of the most rapid fertility transitions in the world. In the 1960s, the fertility rate was nearly eight children per woman, largely driven by the country’s conservative and religious social structure. In contrast, recent decades have seen a dramatic decline, with fertility rates falling to around two children per woman. This sharp reduction can be attributed to sweeping socio-economic reforms, including the expansion of women’s education, shifts in female labor market participation, and broader societal transformations under Vision 2030.</p>
<p>This project aims to analyze and forecast Saudi Arabia’s fertility rate using the ARIMA model. By modeling historical trends and projecting future changes, the study seeks to shed light on the potential implications of fertility dynamics for labor market policies and broader social development strategies in Saudi Arabia.</p>
</section>
<section id="definition-data-source" class="level1">
<h1>Definition &amp; Data Source</h1>
<p>The Total Fertility Rate (TFR) measures the average number of children a woman would have over her lifetime if she were to experience the current age-specific fertility rates throughout her childbearing years. It is expressed as the number of births per woman in a given year.</p>
<p>For this study, the analysis covers the period 1960–2023, utilizing annual data obtained from the World Bank Open Data platform. The dataset provides consistent and internationally comparable fertility indicators, making it a reliable source for examining long-term demographic trends in Saudi Arabia</p>
</section>
<section id="methodolgy" class="level1">
<h1>Methodolgy</h1>
<p>To drive the forecasting model we will transform the dataset from fertility rate to growth rate of fertility rate by using this equation: <span class="math display">\[
\text{Growth Rate}_t = \Delta \ln(\text{Fertility Rate}_t)
\]</span> Additionally, we will conduct differencing to the series with (I=1), to make the series stationary. Finally, we chose AR(4) for this analysis because it passed all the tests.</p>
</section>
<section id="diagnosing" class="level1">
<h1>Diagnosing</h1>
<p>To start the analysis, Referring to the <strong>Figure 1</strong>, the series seems to have a severe downward trend, and a severe variance as well. This is an indication that the series isn’t stationary.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fert_rate_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<section id="data-processing" class="level2">
<h2 class="anchored" data-anchor-id="data-processing">Data Processing</h2>
<p>To address the non-stationarity observed in the fertility rate series, the variable is transformed from levels to growth rates using a log-difference transformation:</p>
<p><span class="math display">\[
\text{Growth Rate}_t = \Delta \ln(\text{Fertility Rate}_t)
\]</span></p>
<p>This transformation substantially improves the visual properties of the series by removing the pronounced trend present in the level data as shown in <strong>Figure 2</strong>. However, despite the improved appearance, visual inspection alone is insufficient to establish stationarity. Therefore, formal unit root tests are conducted to assess whether the transformed series is stationary.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fert_rate_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>Both the Augmented Dickey–Fuller (ADF) test and the DF-GLS test are applied. In this report, greater emphasis is placed on the DF-GLS test, as it is generally more powerful than the standard ADF test, particularly in small samples and in the presence of deterministic components. The results of the DF-GLS test are shown below in <strong>Table 1</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1: DF-GLS Stationarity Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: right;">Statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DF-GLS</td>
<td style="text-align: right;">-0.905</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The absolute value of the DF-GLS t-statistic is 0.905, which is smaller than the 5% critical value of 1.96. As a result, the null hypothesis of a unit root cannot be rejected. This indicates that the growth rate of the fertility rate remains non-stationary, even after log-differencing.</p>
</section>
<section id="differncing" class="level2">
<h2 class="anchored" data-anchor-id="differncing">Differncing</h2>
<p>To achieve stationarity, further differencing is applied to the growth rate series. Specifically, the first difference of the growth rate is taken (I=1):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fert_rate_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>The differenced series in <strong>Figure 3</strong> exhibits a substantial improvement in its time-series properties. Visual inspection suggests that the mean is now stable over time, indicating potential stationarity. However, some variability in the variance remains, which may raise concerns about heteroskedasticity and will be addressed in subsequent diagnostics.</p>
<p>To formally assess stationarity, the same unit root testing procedure is applied to the differenced series, focusing again on the DF-GLS test due to its superior power properties. the results of the test is shown in <strong>Table 2</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2: DF-GLS Stationarity Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: right;">Statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">DF-GLS</td>
<td style="text-align: right;">-2.411</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The absolute value of the DF-GLS t-statistic is 2.411 which exceeds the 5% critical value of 1.96. Consequently, the null hypothesis of a unit root is rejected. This provides strong evidence that the differenced growth rate series is stationary.</p>
<p>Thus, after first differencing, the fertility rate series satisfies the stationarity condition required for subsequent time-series modeling.</p>
</section>
<section id="arima-modeling" class="level2">
<h2 class="anchored" data-anchor-id="arima-modeling">ARIMA modeling</h2>
<p>Having established that the series is integrated of order one (I=1) , the next step is to identify the appropriate ARIMA specification by selecting the autoregressive (p), and moving average (q) orders.</p>
<p>Multiple ARIMA models were estimated and evaluated through an iterative process, including ARIMA(1,1,0), ARIMA(2,1,0), ARIMA(1,1,1), and ARIMA(4,1,0). Model performance was assessed using information criteria (AICc and BIC) as well as residual diagnostics based on the Ljung–Box test.The Ljung–Box test was conducted at lags 8 and 16. The choice of 16 lags follows the standard rule-of-thumb of N/4, where N = 64 in this case. <strong>Table 3</strong> summarizes the estimated coefficients, information criteria, and Ljung–Box test statistics for each candidate model.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3: Comparison of ARIMA Models</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 21%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">AR(1)</th>
<th style="text-align: center;">ARMA(1,1)</th>
<th style="text-align: center;">AR(2)</th>
<th style="text-align: center;">AR(4)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Theta1.SE.</td>
<td style="text-align: center;">0.15 (0.142)</td>
<td style="text-align: center;">0.079 (0.455)</td>
<td style="text-align: center;">0.153 (0.142)</td>
<td style="text-align: center;">-0.148 (0.131)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Theta2.SE.</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">-0.059 (0.144)</td>
<td style="text-align: center;">-0.174 (0.122)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Theta3.SE.</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">-0.462 (0.121)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Theta4.SE.</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">-0.513 (0.128)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Phi1.SE.</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">0.074 (0.431)</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;">N/A</td>
</tr>
<tr class="even">
<td style="text-align: left;">AICc</td>
<td style="text-align: center;">-303.789</td>
<td style="text-align: center;">-301.609</td>
<td style="text-align: center;">-301.748</td>
<td style="text-align: center;">-318.458</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">-299.738</td>
<td style="text-align: center;">-295.642</td>
<td style="text-align: center;">-295.780</td>
<td style="text-align: center;">-308.894</td>
</tr>
<tr class="even">
<td style="text-align: left;">LB8.p.value.</td>
<td style="text-align: center;">17.1 ( 0.01679 )</td>
<td style="text-align: center;">17.24 ( 0.0159 )</td>
<td style="text-align: center;">17.92 ( 0.00643 )</td>
<td style="text-align: center;">7.97 ( 0.09276 )</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LB16.p.value.</td>
<td style="text-align: center;">28.76 (0.01729)</td>
<td style="text-align: center;">28.9 (0.01655)</td>
<td style="text-align: center;">29.67 (0.00847)</td>
<td style="text-align: center;">17.14 (0.14428)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The results indicate the following:</p>
<p>ARIMA(1,1,0): This model performs well in terms of AICc and BIC. However, the Ljung–Box test rejects the null hypothesis of no residual autocorrelation at both lag lengths, indicating that the residuals do not behave as white noise. As a result, the model is deemed inadequate.</p>
<p>ARIMA(1,1,1): Despite competitive information criteria values, this model also fails the Ljung–Box test, rejecting the null hypothesis of white-noise residuals. This suggests remaining serial correlation and model misspecification.</p>
<p>ARIMA(2,1,0): Although this specification improves flexibility relative to the AR(1) model and maintains reasonable AICc and BIC values, it similarly fails the Ljung–Box diagnostic tests, indicating persistent autocorrelation in the residuals.</p>
<p>ARIMA(4,1,0): This model delivers superior overall performance. It achieves competitive information criteria values while, crucially, failing to reject the null hypothesis of the Ljung–Box test at both lag lengths. This implies that the residuals behave as white noise, satisfying the key assumption of model adequacy.</p>
</section>
</section>
<section id="ar4" class="level1">
<h1>AR(4)</h1>
<p>Having selected the ARIMA(4,1,0) specification, the model’s adequacy is assessed through an examination of coefficient properties, residual behavior, and potential violations of key assumptions. The AR(4) specification used throughout the analysis is given by:</p>
<p>[ y_t = ,y_{t-1} + ,y_{t-2} + ,y_{t-3} + ,y_{t-4} + _t ]</p>
<section id="coefficients" class="level2">
<h2 class="anchored" data-anchor-id="coefficients">Coefficients</h2>
<p>As a preliminary diagnostic, the necessary and sufficient conditions for stationarity of the autoregressive component are examined.</p>
<p>– Sum of Coefficients = -1.297 .</p>
<p>– Sum of absolute values of Coefficients = 1.297</p>
<p>The sum of coefficients does not violate the necessary condition, while the sum of absolute coefficients exceeds unity, meaning the sufficient condition for stationarity is not satisfied. As expected for higher-order AR processes, these conditions alone are inconclusive and do not provide definitive evidence regarding the stability of the process. Consequently, further diagnostics based on residual behavior are required.</p>
</section>
<section id="residual-plot" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot">Residual Plot</h2>
<p>The residuals from the AR(4) model fluctuate around a zero mean, indicating that the model successfully captures the conditional mean dynamics. However, visual inspection reveals a noticeable change in variance beginning around the year 2000, suggesting a potential violation of the homoskedasticity assumption.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fert_rate_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="acf-pacf" class="level2">
<h2 class="anchored" data-anchor-id="acf-pacf">ACF &amp; PACF</h2>
<p>The autocorrelation and partial autocorrelation functions of the residuals show no statistically significant spikes outside the confidence bounds. This confirms that the AR(4) model adequately removes serial correlation and that the residuals behave as white noise in the mean.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fert_rate_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Figure 5: ACF &amp; PACF of AR4 model</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="heteroskedasticity-test" class="level2">
<h2 class="anchored" data-anchor-id="heteroskedasticity-test">Heteroskedasticity Test</h2>
<p>Given the visual evidence of changing variance, Engle’s ARCH LM test is applied to formally assess the presence of conditional heteroskedasticity. A lag length of 10 is chosen as a conservative diagnostic choice given the sample size, with results shown in <strong>Table 4</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 4: ARCH LM Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">ARCH.LM.test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">P-Value</td>
<td style="text-align: left;">2.33e-05</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The ARCH Engle’s test statistic has a p-value of 0 and it is &lt; 0.05. This rejects the null hypothesis of ARCH effect, and confirming that the series has Heteroskedasticity.</p>
<p>The detection of ARCH effects implies that while the ARIMA(4,1,0) model adequately captures the conditional mean dynamics, it fails to account for time-varying volatility. To obtain efficient and unbiased inference—particularly for volatility dynamics—a GARCH-type specification is required.</p>
<p>That said, the ARIMA model remains informative for short-run forecasting of the conditional mean, especially when volatility dynamics are not the primary object of interest. Subsequent analysis will therefore extend the model by incorporating a GARCH structure to appropriately model the variance process.</p>
</section>
</section>
<section id="garch-extension-modeling-time-varying-volatility" class="level1">
<h1>GARCH Extension: Modeling Time-Varying Volatility</h1>
<p>The presence of significant ARCH effects in the residuals of the AR(4) model indicates that, while the conditional mean dynamics are well specified, the assumption of constant variance is violated. To account for volatility clustering and time-varying uncertainty, the model is extended by specifying a GARCH process for the conditional variance. Given the sample size (64 observations), a GARCH(1,1) specification is adopted, which is widely used and typically sufficient to capture persistent volatility dynamics.</p>
<section id="estimate-ar4garch11" class="level2">
<h2 class="anchored" data-anchor-id="estimate-ar4garch11">Estimate AR(4)–GARCH(1,1)</h2>
<p>Building on the previous results, the ARIMA(4,1,0) specification is retained to model the conditional mean dynamics of the series, as it adequately removes serial correlation in the residuals. However, diagnostic evidence indicates the presence of time-varying volatility, motivating an extension of the model to explicitly account for conditional heteroskedasticity.</p>
<p>Accordingly, the model is specified as an AR(4) process in the mean combined with a GARCH(1,1) process for the conditional variance. The estimated variance parameters from the GARCH(1,1) specification are reported in <strong>Table 5</strong>, and the full model is summarized by the mean and variance equations presented below. This framework allows the dynamics of the series to be decomposed into systematic persistence in the mean and persistent volatility in the variance, providing a more complete representation of both the level and uncertainty of the process.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 5: GARCH(1,1) Variance Parameters</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">omega</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">alpha1</td>
<td style="text-align: right;">0.4338</td>
</tr>
<tr class="odd">
<td style="text-align: left;">beta1</td>
<td style="text-align: right;">0.5652</td>
</tr>
<tr class="even">
<td style="text-align: left;">alpha1 + beta1</td>
<td style="text-align: right;">0.9990</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The estimated GARCH(1,1) variance parameters indicate strong and highly persistent volatility dynamics in the series. The ARCH coefficient, (_1 =) 0.4338, captures the short-run response of conditional variance to unexpected shocks and suggests that large innovations have a substantial immediate impact on volatility. The GARCH coefficient, (_1 =) 0.5652, reflects persistence in volatility, indicating that periods of elevated uncertainty tend to persist over time.</p>
<p>The sum of the ARCH and GARCH coefficients, (_1 + _1 =) 0.999, is extremely close to unity, implying near-integrated volatility dynamics. While the condition (_1 + _1 &lt; 1) technically ensures covariance stationarity of the variance process, the proximity to one suggests that shocks to volatility decay very slowly and have long-lasting effects. This behavior is consistent with pronounced volatility clustering.</p>
<p>The estimated constant term in the variance equation, (=) 3^{-6}, is effectively zero, indicating that the evolution of volatility is largely driven by past shocks and past conditional variance rather than by a fixed long-run variance level.</p>
<p>Overall, these results confirm that extending the AR(4) mean specification with a GARCH(1,1) variance process is necessary to appropriately model time-varying volatility and to obtain reliable inference and forecast uncertainty.</p>
<p>The AR(4)–GARCH(1,1) model is formally specified below through its conditional mean and variance equations.</p>
<p>The mean equation remains the selected AR(4) specification:</p>
<p>[ y_t = ,y_{t-1} + ,y_{t-2} + ,y_{t-3} + ,y_{t-4} + _t ]</p>
<p>The conditional variance follows a GARCH(1,1) process:</p>
<p>[ <em>t^2 = 0.4338,</em>{t-1}^2 + 0.5652,_{t-1}^2 ]</p>
</section>
<section id="residual-diagnostics-and-model-adequacy" class="level2">
<h2 class="anchored" data-anchor-id="residual-diagnostics-and-model-adequacy">Residual Diagnostics and Model Adequacy</h2>
<p>To assess model adequacy, we examine the standardized residuals from the AR(4)–GARCH(1,1) model. <strong>Figure 6</strong> shows that the standardized residuals fluctuate around zero without visible persistence. Also, it indicates no meaningful autocorrelation in the standardized residuals, suggesting that the mean dynamics are adequately captured.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fert_rate_files/figure-html/stdres-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>To formally confirm the absence of serial correlation, Ljung–Box tests are applied to the standardized residuals at lags 8 and 16. The results, reported in <strong>Table 6</strong>, fail to reject the null hypothesis of no autocorrelation at conventional significance levels, confirming that the residuals behave as white noise in the mean.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 6: Ljung–Box tests on standardized residuals (post-GARCH)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: right;">Statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ljung–Box (lag 8)</td>
<td style="text-align: right;">8.325</td>
<td style="text-align: right;">0.402</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ljung–Box (lag 16)</td>
<td style="text-align: right;">24.258</td>
<td style="text-align: right;">0.084</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="forecasting" class="level1">
<h1>Forecasting</h1>
<p>Having established the adequacy of the AR(4) and AR(4)–GARCH(1,1) specifications, this section presents short-run forecasts of the fertility rate. Forecasts are generated over a 4-period horizon. The AR(4) model provides forecasts based solely on conditional mean dynamics, while the AR(4)–GARCH(1,1) model incorporates time-varying volatility, allowing forecast uncertainty to evolve over time. Comparing these forecasts highlights the role of conditional heteroskedasticity in shaping forecast behavior and uncertainty.</p>
<p><strong>Figure 7</strong> &amp; <strong>Table 7</strong> compare forecasted fertility rates generated by the AR(4) model and the AR(4)–GARCH(1,1) model over the forecast horizon. Although both models share the same conditional mean structure, their forecasts diverge markedly once projected back into fertility levels.</p>
<p>The AR(4) model predicts a gradual decline in fertility rates, with minor short-run fluctuations. This pattern reflects the persistence captured by the autoregressive structure and extrapolates recent downward dynamics in the growth rate of fertility. Because the AR(4) model assumes constant variance, forecast paths are driven solely by mean dynamics, resulting in relatively smooth and conservative projections.</p>
<p>In contrast, the AR(4)–GARCH(1,1) model produces a steadily increasing fertility path. This divergence arises because the GARCH component captures highly persistent volatility, as evidenced by the near-unit volatility persistence (alpha + beta ≈1). When forecasts are iteratively transformed from growth rates back into fertility levels, periods of elevated conditional variance amplify forecast uncertainty and compound upward movements in the level series. As a result, even small positive expected growth rates translate into increasingly larger fertility projections over time.</p>
<p>Importantly, this difference does not imply that the GARCH model fundamentally predicts higher mean fertility growth. Rather, it highlights how persistent volatility interacts with nonlinear level transformations, causing forecasts to diverge despite identical mean specifications. The AR(4)–GARCH(1,1) model therefore produces more dispersed and dynamic level forecasts, reflecting uncertainty accumulation rather than deterministic trend reversal.</p>
<p>Overall, the comparison underscores that incorporating time-varying volatility can materially affect long-horizon level forecasts, even when point forecasts of the growth rate are similar. This finding emphasizes the importance of accounting for volatility dynamics when forecasting demographic variables that are reconstructed through nonlinear transformations.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 7: Forecasted Growth and Fertility Rates — AR(4) vs AR(4)–GARCH(1,1) (7-step horizon)</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: right;">AR4_Growth</th>
<th style="text-align: right;">GARCH_Growth</th>
<th style="text-align: right;">AR4_Fertility</th>
<th style="text-align: right;">GARCH_Fertility</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2024</td>
<td style="text-align: right;">0.0363</td>
<td style="text-align: right;">0.0642</td>
<td style="text-align: right;">2.363</td>
<td style="text-align: right;">2.426</td>
</tr>
<tr class="even">
<td style="text-align: right;">2025</td>
<td style="text-align: right;">-0.0119</td>
<td style="text-align: right;">0.0614</td>
<td style="text-align: right;">2.335</td>
<td style="text-align: right;">2.575</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2026</td>
<td style="text-align: right;">-0.0517</td>
<td style="text-align: right;">0.0304</td>
<td style="text-align: right;">2.214</td>
<td style="text-align: right;">2.654</td>
</tr>
<tr class="even">
<td style="text-align: right;">2027</td>
<td style="text-align: right;">-0.0646</td>
<td style="text-align: right;">0.0251</td>
<td style="text-align: right;">2.071</td>
<td style="text-align: right;">2.720</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fert_rate_files/figure-html/fertility-forecast-plot-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Figure 7: Forecasted fertility rates from AR(4) and AR(4)–GARCH(1,1) models.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This report examined the dynamics of fertility in Saudi Arabia using a time-series framework that jointly models mean behavior and time-varying uncertainty. After establishing non-stationarity in the fertility rate series, the analysis proceeded by modeling fertility growth and identifying an ARIMA(4,1,0) specification as the most appropriate representation of the conditional mean. Diagnostic tests confirmed that the AR(4) structure adequately removed serial correlation from the residuals, but also revealed the presence of significant conditional heteroskedasticity.</p>
<p>To address this limitation, the model was extended to an AR(4)–GARCH(1,1) specification. The GARCH results indicated highly persistent volatility, with the sum of the ARCH and GARCH parameters close to unity, implying that shocks to fertility growth uncertainty decay slowly over time. This finding highlights that fertility dynamics in Saudi Arabia are shaped not only by expected trends but also by prolonged periods of uncertainty, likely reflecting structural transitions in labor markets, housing conditions, and social norms.</p>
<p>Short-run forecasts illustrate the practical importance of accounting for volatility. While the AR(4) model projects declining fertility levels after 2024, the AR(4)–GARCH(1,1) model generates rising fertility paths over the same horizon. This divergence underscores that ignoring time-varying uncertainty can materially alter conclusions about future fertility trajectories, particularly when forecasts are reconstructed in levels. The results therefore caution against reliance on mean-only projections for demographic planning.</p>


</section>

</main> <!-- /main -->
<script src="assets/js/typed-role.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>